"""tags de animo en reflections

Revision ID: 5b1d61ba7750
Revises: 4bda7d798cb4
Create Date: 2026-07-18 16:11:03.929214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b1d61ba7750'
down_revision: Union[str, Sequence[str], None] = '4bda7d798cb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reflections', sa.Column('mood_tags', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reflections', 'mood_tags')
    # ### end Alembic commands ###
