"""recordatorios de manana y noche separados

Revision ID: 725ae2b49f65
Revises: 5b1d61ba7750
Create Date: 2026-07-19 13:39:29.238361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '725ae2b49f65'
down_revision: Union[str, Sequence[str], None] = '5b1d61ba7750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default en las columnas nuevas para no romper filas existentes
    # de app_settings (NOT NULL sin default falla si ya hay usuarios).
    op.add_column(
        'app_settings',
        sa.Column('morning_reminder_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    op.add_column(
        'app_settings',
        sa.Column('morning_reminder_time', sa.Time(), nullable=False, server_default=sa.text("'07:00:00'")),
    )
    op.add_column(
        'app_settings',
        sa.Column('night_reminder_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    op.add_column(
        'app_settings',
        sa.Column('night_reminder_time', sa.Time(), nullable=False, server_default=sa.text("'21:00:00'")),
    )
    op.drop_column('app_settings', 'notification_enabled')
    op.drop_column('app_settings', 'notification_time')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('notification_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('app_settings', sa.Column('notification_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('app_settings', 'night_reminder_time')
    op.drop_column('app_settings', 'night_reminder_enabled')
    op.drop_column('app_settings', 'morning_reminder_time')
    op.drop_column('app_settings', 'morning_reminder_enabled')
    # ### end Alembic commands ###
